#spring:
#  config:
#    import: configserver:http://localhost:8082/
#  cloud:
#    config:
#      name: Demo-prod
#
#
#spring:
#  config:
#    import: configserver:http://localhost:8082/
#  cloud:
#    config:
#      name: Demo-dev
#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          #issuer-uri: https://upis-auth.uitgis.vn
#          issuer-uri: http://103.82.133.193:8900
#  mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER
#  mysql.datasource:
#    url: jdbc:mysql://103.82.133.193:3306/podcast?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
#    username: root
#    password: 123456@
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 50
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      minimum-idle: 2
#      validation-timeout: 20000
#  jpa:
#    #database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    format_sql: true
#eureka:
#  instance:
#    hostname: 103.82.133.193
#    statusPageUrl: http://103.82.133.193:8761/eureka/info
#    healthCheckUrl: http://103.82.133.193:8761/eureka/health
#  client:
#    serviceUrl:
#      defaultZone: http://103.82.133.193:8761/eureka/
#
##app:
##  swagger:
##    plugin: true
#server:
#  port: 8899
#  forward-headers-strategy: framework
## Swagger config
#springdoc:
#  swagger-ui:
#    enabled: true
#    path: 'com.uit.podcast.controller'
#    tryItOutEnabled: false
#    syntaxHighlight:
#      activated: true

#------------------
#spring:
#  config:
#    import: configserver:http://localhost:8082/
#  cloud:
#    config:
#      name: Demo-dev
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://103.82.133.193:8900
  mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER
  mysql.datasource:
    url: jdbc:mysql://mysql-bive:3306/payment?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    #url: jdbc:mysql://103.82.133.193:9091/payment?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 2
      validation-timeout: 20000
  jpa:
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    format_sql: true
eureka:
  instance:
    hostname: 103.82.133.193
    statusPageUrl: http://103.82.133.193:8761/eureka/info
    healthCheckUrl: http://103.82.133.193:8761/eureka/health
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${registry.host:103.82.133.193}:${registry.port:8761}/eureka/

#app:
#  swagger:
#    plugin: true
#server:
#  port: 8899
#  forward-headers-strategy: framework
# Swagger config
springdoc:
  swagger-ui:
    enabled: true
    path: 'com.uit.podcast.controller'
    tryItOutEnabled: false
    syntaxHighlight:
      activated: true

server:
  client:
    bive:
      url: https://api.bevi.click
      redirect: https://prod.d1vcb1w1b7j9n0.amplifyapp.com/
      pack:
        - 7000
        - 8000
        - 9000
    podcast:
      url: https://PODCAST-SERVICE
      redirect: http://localhost:8082

payment:
  vqr:
    base-url : https://api.vietqr.org
    username: customer-vietqrtest-bive
    password: Vietqrtestbive
  jwt:
    secret-key: 'Wm9Qd1h3d0xZb2NQd0R5ZkJ1Q1h5aGZ3Z2l4dFZ5QkR5eVJ3T1d3aG1zU2h3eUZ4c3p3b1lVbVh5Z0J2b3RzU2pQd1dXbQ=='
    expiration: 60000
  client:
    username: customer-bive-user26534
    password: Y3VzdG9tZXItYml2ZS11c2VyMjY1MzQ=
  signature: my-signature